name: Build and Test TALauncher

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # CI requires a clean working tree due to checkGitStatus task

    - name: Run unit tests
      run: ./gradlew :app:unitTestSuite --no-daemon --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 30

    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: |
          app/build/reports/lint-*.html
        retention-days: 30

    - name: Comment on PR with APK download links
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          try {
            const runId = context.runId;
            const repo = context.repo;

            const comment = `## APK Build Artifacts

            The debug APK has been built successfully. Download from workflow artifacts:

            • [Open Workflow Artifacts](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId})

            Available Downloads:
            - debug-apk (Main application debug build)
            - test-reports (Unit test results)
            - lint-reports (Code quality reports)

            Note: You must be logged into GitHub to download artifacts. Artifacts expire after 30 days.`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: repo.owner,
              repo: repo.repo,
              body: comment
            });

            console.log('Successfully added PR comment with download links');
          } catch (error) {
            console.log('Unable to comment on PR (likely due to permissions):', error.message);
            console.log('Build artifacts are still available in the Actions tab');
          }

