name: Build and Test TALauncher

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup environment
      run: |
        # Disable git status check for CI
        export SKIP_GIT_STATUS_CHECK=true
        echo "SKIP_GIT_STATUS_CHECK=true" >> $GITHUB_ENV

    - name: Run unit tests
      run: ./gradlew test --no-daemon --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Build UI tests APK
      run: ./gradlew :uitests:assembleDebugAndroidTest --no-daemon --stacktrace

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Upload UI test APK
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-apk
        path: uitests/build/outputs/apk/androidTest/debug/uitests-debug-androidTest.apk
        retention-days: 30

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          app/build/reports/tests/
          uitests/build/reports/tests/
          app/build/test-results/
          uitests/build/test-results/
        retention-days: 30

    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: |
          app/build/reports/lint-*.html
          uitests/build/reports/lint-*.html
        retention-days: 30


  # Instrumentation tests would require an emulator - skipping for now
  # but can be added later if needed
  # instrumentation-tests:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'
  #
  #   - name: Setup Android SDK
  #     uses: android-actions/setup-android@v3
  #
  #   - name: Start Android Emulator
  #     uses: reactivecircus/android-emulator-runner@v2
  #     with:
  #       api-level: 29
  #       script: ./gradlew :uitests:connectedAndroidTest --no-daemon